### ISSUE TITLE
Love Marketplace

### ISSUE THREAD

**Issue by RedWilly** [marcolub/nft-marketplace#1]
Hey - Love the marketplace but i tried testing it to buy the NFT you have put onsale but didnt work for some reason on the http://nft-marketplace-six-nu.vercel.app/

Anyways could you add more docs / infor in the readme.md section

**Comment by marcolub** [comment]
Hey , thank you!
I have made the marketplace for a project of mine, probably you have to set some enviroment variables in your Vercel project
